web: vendor/bin/heroku-php-apache2 public/
worker: php artisan queue:work --tries=3 --timeout=90
reverb: php artisan reverb:start --host="0.0.0.0" --port=${PORT:-8080}
release: php artisan migrate --force && php artisan storage:link
